### ISSUE TITLE
Wiring guide

### ISSUE THREAD

**Issue by sirspamalot** [ammolytics/projects#2]
I'd appreciate a small wiring guide as in "connect pin X to Featherboard pin Y" as it's not really obvious whether it has to be wired via I2C or SPI

**Comment by erichiggins** [comment]
Hi!  I linked to the wiring guide provided by Adafruit in the README, but here's the link again in case you missed it.
https://learn.adafruit.com/adafruit-lis3dh-triple-axis-accelerometer-breakout?view=all

I didn't include one here because, frankly, they did a better job that I could have.

The code provided here utilizes I2C, but SPI is also an option -- you'll just need to change the code very slightly and the Adafruit guide also does an excellent job of explaining those differences.

I hope this helps!
