### ISSUE TITLE
Trickler doesn´t work

### ISSUE THREAD

**Issue by boki1397** [ammolytics/projects#47]
Hello at all.
I´m a greenhorn with raspberry and programming and i need help.

first I set up and built everything according to the instructions.

i have connected the raspberry to the app.

after entering the weight and the start button, the trickler does not run.

if I drive the diode directly with electricity, the motor runs

i have no idea where the error is.

can someone help me?

I can also send the raspberry logs.

sorry for my bad English. I'm from Germany

Thank you for your help in advance.

**Comment by erichiggins** [comment]
Hey @boki1397 !

It's possible that there's an issue which pin you're connected to for activating the motor.

If you'd like to join us on Discord, there are a lot of other people who have built Open Tricklers that can help out by sharing their experience. I think we may even have a few other German-speakers in there too!
https://discord.gg/WqTbyK2

Otherwise, perhaps you can share a photo of your build so I can see which pins you're connected to on the Raspberry Pi?

**Comment by erichiggins** [comment]
Has your issue been resolved?

**Comment by erichiggins** [comment]
Marking this as closed since I haven't heard back.
